---
# Master playbook

- import_playbook: 01-update.yml
- import_playbook: 02-ssh-hardening.yml
- import_playbook: 03-users.yml
- import_playbook: 04-fail2ban.yml
- import_playbook: 05-firewall.yml
- import_playbook: 06-backup-files.yml
- import_playbook: 07-backup-database.yml
- import_playbook: 08-docker.yml
- import_playbook: 09-monitoring.yml
- import_playbook: 10-disable-services.yml
- import_playbook: 11-kernel-hardening.yml
- import_playbook: 12-logrotate.yml
